### PR TITLE
Change trust root to trust anchor in draft-sheffer-wimse-s2s-protocol.md

### PR DESCRIPTION
**Pull request by kenmccracken-google**
Aligns with Trust Anchor terminology as used in [rfc5280](https://datatracker.ietf.org/doc/html/rfc5280).

### CODE REVIEW

**Comment by yaronf** [comment]
I would defer to @jsalowey here, who wrote the original text and I suspect is also more of an expert on this terminology.

**Comment by kenmccracken-google** [comment]
This seems to have bitrot.  Please refer to https://github.com/ietf-wg-wimse/draft-ietf-wimse-s2s-protocol/pull/58 instead.

**Comment by yaronf** [comment]
@kenmccracken-google Hi Ken, why did you force-push into the "main" branch?

**Comment by bc-pi** [comment]
> @kenmccracken-google Hi Ken, why did you force-push into the "main" branch?

is that what happened here? I don't see where you see that that happened?

**Comment by yaronf** [comment]
@bc-pi I see it on the GH UI right above here, but apparently it failed because the commit log doesn't show it.

**Comment by kenmccracken-google** [comment]
I apologize, the force-push was an error, I probably clicked the wrong options.  AFAICT the outcome is not in the commit history.

**Pull request closed without merging**
